check_hunters/core/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import re_path, include, path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse
import datetime
from django.core.management import execute_from_command_line
from accounts.views import ClientUpdateView
from checks.views import reset_database, current_datetime


urlpatterns = [
    re_path(r'^$', login_required(TemplateView.as_view(template_name='home.html')), name='home'),
    re_path(r'accounts/', include('django.contrib.auth.urls')),
    re_path(r'admin/', admin.site.urls),
    re_path(r'check_accounts/', include('accounts.urls')),
    re_path(r'checks/', include('checks.urls')),
    re_path(r'utests/', current_datetime),
    re_path(r'resetdb/', reset_database),
    re_path(r'reports/', include('reports.urls')),
    re_path(r'company_configurations/(?P<pk>\d+)/$', ClientUpdateView.as_view(), name='client_update'),
]

check_hunters/reports/urls.py
# reports urls

from django.urls import re_path
from . import views

app_name = 'reports'

# url patterns match in a procedural way, so put the most specific ones at the top
urlpatterns = [
    re_path(r'paid_check_data$', views.paid_check_data, name='paid_check_data'),
    re_path(r'num_check_data$', views.num_checks_data, name='num_checks_data'),
    re_path(r'sent_letters_data$', views.sent_letters_data, name='sent_letters_data'),
    re_path(r'$', views.general_report, name='general_report'),
]

check_hunters/reports/models.py
from django.db import models

# Create your models here.

check_hunters/reports/forms.py
from django import forms

class FilterForm(forms.Form):
    primary_field = forms.CharField(label='Primary Field', max_length=100)
    secondary_field = forms.CharField(label='Secondary Field', max_length=100)

check_hunters/reports/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from accounts.models import Account, Bank, Client
from checks.models import Check
from datetime import datetime

from .forms import FilterForm

def filter_by_to_client(qs, request):
    client = request.user.client
    if client:
        return qs.filter(to_client=client)
    return qs

@login_required
def general_report(request):
    return render(request, 'generalreports.html')


@login_required
def paid_check_data(request):
    checks = filter_by_to_client(Check.objects.all(), request)
    return_data = []

    paid_checks = {}
    paid_checks["Name"] = "Paid Checks"
    paid_checks["Count"] = 0

    unpaid_checks = {}
    unpaid_checks["Name"] = "Unpaid Checks"
    unpaid_checks["Count"] = 0

    outstanding_checks = {}
    outstanding_checks["Name"] = "Outstading Checks"
    outstanding_checks["Count"] = 0

    for check in checks:
        if (check.paid_date == None):
            unpaid_checks["Count"] += 1
        else:
            paid_checks["Count"] += 1
        if (check.letter_3_sent != 0):
            outstanding_checks["Count"] += 1

    return_data.append(paid_checks)
    return_data.append(unpaid_checks)
    return_data.append(outstanding_checks)

    return JsonResponse(return_data, safe=False)


@login_required
def sent_letters_data(request):
    checks = filter_by_to_client(Check.objects.all(), request)

    letter_1_sent = 0
    letter_2_sent = 0
    letter_3_sent = 0
    letter_1_notsent = 0
    letter_2_notsent = 0
    letter_3_notsent = 0

    today = datetime.today().strftime('%Y-%m-%d')

    for check in checks:
        if (check.paid_date == None):
            if (str(check.letter_1_send_date) == today and check.letter_1_sent == 1):
                letter_1_sent += 1
            elif (str(check.letter_2_send_date) == today and check.letter_2_sent == 1):
                letter_2_sent += 1
            elif (str(check.letter_3_send_date) == today and check.letter_3_sent == 1):
                letter_3_sent += 1
            elif (str(check.letter_1_send_date) == today and check.letter_1_sent == 0):
                letter_1_notsent += 1
            elif (str(check.letter_2_send_date) == today and check.letter_2_sent == 0):
                letter_2_notsent += 1
            elif (str(check.letter_3_send_date) == today and check.letter_3_sent == 0):
                letter_3_notsent += 1
            else:
                continue

    return_data = [{"lettertype": "letter 1's sent", "letterssent": letter_1_sent},
     {"lettertype": "letter 2's sent", "letterssent": letter_2_sent},
     {"lettertype": "letter 3's sent", "letterssent": letter_3_sent},
     {"lettertype": "letter 1's not sent", "letterssent": letter_1_notsent},
     {"lettertype": "letter 2's not sent", "letterssent": letter_2_notsent},
     {"lettertype": "letter 3's not sent", "letterssent": letter_3_notsent}]
    return JsonResponse(return_data, safe=False)

@login_required
def num_checks_data(request):
    checks = filter_by_to_client(Check.objects.all(), request)
    client = request.user.client
    if client:
        clients = [client,]
    else:
        clients = Client.objects.all()
    client_count_dict = {}
    client_ids_to_names = {}
    for client in clients:

        client_ids_to_names[client.id] = client.name
        client_count_dict[client.name] = 0

    for check in checks:
        if check.paid_date == None:
            client_count_dict[client_ids_to_names[check.to_client_id]] += 1

    return_data = { "children": []}

    for key, value in client_count_dict.items():
        temp_dict = {}
        temp_dict["Name"] = key
        temp_dict["Count"] = value
        return_data["children"].append(temp_dict)

    return JsonResponse(return_data, safe=False)

check_hunters/reports/templates/generalreports.html
{% extends "base.html" %}
{% load static %}
{% load render_table from django_tables2 %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'css/piechart.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/barchart.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/bubblechart.css' %}"/>
  <link rel="stylesheet" href="{% static 'css/reports.css' %}"/>
  <script src="https://d3js.org/d3.v4.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
  <script type="text/javascript" src="{% static 'js/piechart.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/barchart.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bubblechart.js' %}"></script>
{% endblock %}

{% load crispy_forms_tags %}
{% block content %}



  <div class="container">
      <div class="row">
        <div class="col-sm-10 offset-sm-1 offset-md-3 col-md-6">
            <h1>Reports</h1>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-10 offset-sm-1 offset-md-1 col-md-10">
            <h3> Paid vs Unpaid Checks </h3>
            <div class="graph" id="graph"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-10 offset-sm-1 offset-md-1 col-md-10">
            <h3> Number of Unpaid Checks Per Client </h3>
            <div class="bubblechart" id="bubblechart"></div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-10 offset-sm-1 offset-md-1 col-md-10">
            <h3> Letters Sent Today </h3>
            <div class="barchart" id="barchart"></div>
        </div>
      </div>
  </div>

  <script type="text/javascript">

    // create the donut template
    var donut = donutChart()
        .width(960)
        .height(500)
        .cornerRadius(3)
        .padAngle(0.015)
        .variable('Count')
        .category('Name');

    // create the donut chart parsing data from the backend "api"
    function createDonutChart() {
    d3.json("{% url 'reports:paid_check_data' %}", function(error, data) {
        if (error) throw error;
        d3.select('.graph')
            .datum(data)
            .call(donut);
    });
  }

  // create the bar graph parsing data from the backend "api"
  function createBarChart() {
    barChart("{% url 'reports:sent_letters_data' %}")
  }

  //create a bubble chart parsing data from the backend "api"
  function createBubbleChart() {
    bubbleChart("{% url 'reports:num_checks_data' %}")
  }

  // function that handles creating the charts when the window loads
  function startUp() {
    createDonutChart();
    createBarChart();
    createBubbleChart();
  }

  //initialize the charts when loading the page
  window.onload = startUp;

  </script>

{% endblock %}