check_hunters/accounts/urls.py
# account urls

from django.urls import re_path
from .views import *

app_name = 'accounts'

urlpatterns = [
    re_path(r'routing_num/add$', BankCreateView.as_view(), name='bank_create'),
    re_path(r'update/(?P<pk>\d+)/$', AccountUpdateView.as_view(), name='update'),
    re_path(r'add$', AccountCreateView.as_view(), name='create'),
    re_path(r'$', AccountListView.as_view(), name='list'),
]

check_hunters/checks/urls.py
# check urls

from django.urls import re_path
from .views import *

app_name = 'checks'

urlpatterns = [
    re_path(r'update/(?P<pk>\d+)/$', CheckUpdateView.as_view(), name='update'),
    re_path(r'add$', CheckCreateView.as_view(), name='create'),
    re_path(r'print_letters$', PrintLettersView.as_view(), name='print_letters'),
    re_path(r'$', CheckListView.as_view(), name='list'),
]

check_hunters/core/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import re_path, include, path
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse
import datetime
from django.core.management import execute_from_command_line
from accounts.views import ClientUpdateView
from checks.views import reset_database, current_datetime


urlpatterns = [
    re_path(r'^$', login_required(TemplateView.as_view(template_name='home.html')), name='home'),
    re_path(r'accounts/', include('django.contrib.auth.urls')),
    re_path(r'admin/', admin.site.urls),
    re_path(r'check_accounts/', include('accounts.urls')),
    re_path(r'checks/', include('checks.urls')),
    re_path(r'utests/', current_datetime),
    re_path(r'resetdb/', reset_database),
    re_path(r'reports/', include('reports.urls')),
    re_path(r'company_configurations/(?P<pk>\d+)/$', ClientUpdateView.as_view(), name='client_update'),
]

check_hunters/reports/urls.py
# reports urls

from django.urls import re_path
from . import views

app_name = 'reports'

# url patterns match in a procedural way, so put the most specific ones at the top
urlpatterns = [
    re_path(r'paid_check_data$', views.paid_check_data, name='paid_check_data'),
    re_path(r'num_check_data$', views.num_checks_data, name='num_checks_data'),
    re_path(r'sent_letters_data$', views.sent_letters_data, name='sent_letters_data'),
    re_path(r'$', views.general_report, name='general_report'),
]

check_hunters/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width">
    <title> Check Hunters </title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <!-- Favicon -->
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    {% block stylesheets %}
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <img src="{% static 'img/checkmark.png' %}" alt="" id="checkmark"/>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

        {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
          {% if user.client %}
              <li>
                <a class="nav-link" href="{% url 'client_update' user.client.pk %}">Company Settings</a>
              </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:list' %}">Accounts</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'checks:list' %}">Checks</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'checks:print_letters' %}">Print Letters</a>
            </li>
          {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'reports:general_report' %}">Reports</a>
            </li>
          {% if user.can_access_admin %}
              <li>
                <a class="nav-link" href="{% url 'admin:index' %}">Site Admin</a>
              </li>
          {% endif %}
              <li>
              <a class="nav-item nav-link right" href="{% url 'logout' %}?next=/accounts/login">Logout</a>
             </li>
      {% endif %}
          </ul>
        </div>
      </nav>
      {% block content %}
      {% endblock %}
      <footer>
          <p> Check Hunters Inc., Copyright &copy; 2018 </p>
      </footer>
  </body>
</html>

check_hunters/core/templates/home.html
{% extends "base.html" %}
{% load static %}
{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'css/home.css' %}"/>
{% endblock %}

{% block content %}
<div class="check-hunters-image" style="background-image: url({% static 'img/writingcheck.jpg' %});"></div>


<div class="check-hunters-title" >
    <img id="logo" class="img-fluid" src="{% static 'img/logo.png' %}" alt="logo"/>
    <button type="button" onclick="location.href = {% url 'reports:general_report' %}" id="reports-btn" class="btn btn-primary">View Reports</button>
</div>
{% endblock %}